### ISSUE TITLE
failed to run fsa_test.py

### ISSUE THREAD

**Issue by ahban** [k2-fsa/k2#1022]
When run `k2/python/tests/fsa_test.py`, it shows the following message. I think it failed.
```
$ python fsa_test.py 
.fsa= 0 1 2 [ ] -1.2
0 2 10 [ 10 ] -2.2
1 6 1 [ ] -3.2
1 3 3 [ 11 12 ] -4.2
2 6 2 [ ] -5.2
2 4 2 [ ] -6.2
3 6 3 [ ] -7.2
5 0 1 [ 13 ] -8.2
6 8 -1 [ ] -9.2
7 8 -1 [ ] 0
8
...fsa1 =  
fsa1 =  
fsa1 =  
.[F] /home/ddp-aban/soft/src/k2/k2/csrc/fsa_utils.cu:95:k2::Fsa k2::K2FsaFromStream(std::istringstream&, int32_t, k2::Array2<int>*, int32_t, k2::Ragged<int>*) Invalid line:             1, final state has already been read, expected no more input.


[ Stack-Trace: ]
/home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/k2/lib64/libk2_log.so(k2::internal::GetStackTrace()+0x34) [0x7f71e39c4174]
/home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/k2/lib64/libk2context.so(k2::internal::Logger::~Logger()+0x2a) [0x7f71e859a35a]
/home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/k2/lib64/libk2context.so(k2::FsaFromString(std::string const&, bool, int, k2::Array2<int>*, int, k2::Ragged<int>*)+0xad2) [0x7f71e8648b52]
/home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/_k2.cpython-38-x86_64-linux-gnu.so(+0x60ae1) [0x7f71e97d2ae1]
/home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/_k2.cpython-38-x86_64-linux-gnu.so(+0x30d54) [0x7f71e97a2d54]
python(+0x13c00e) [0x55f1da18a00e]
python(_PyObject_MakeTpCall+0x3bf) [0x55f1da17f13f]
python(_PyEval_EvalFrameDefault+0x546a) [0x55f1da229e0a]
python(_PyEval_EvalCodeWithName+0x260) [0x55f1da21a600]
python(_PyFunction_Vectorcall+0x534) [0x55f1da21bb64]
python(+0x166b2e) [0x55f1da1b4b2e]
python(_PyEval_EvalFrameDefault+0x4f83) [0x55f1da229923]
python(_PyFunction_Vectorcall+0x1b7) [0x55f1da21b7e7]
python(+0x166b2e) [0x55f1da1b4b2e]
python(_PyEval_EvalFrameDefault+0x71b) [0x55f1da2250bb]
python(_PyFunction_Vectorcall+0x1b7) [0x55f1da21b7e7]
python(_PyEval_EvalFrameDefault+0x4c0) [0x55f1da224e60]
python(_PyEval_EvalCodeWithName+0x260) [0x55f1da21a600]
python(_PyFunction_Vectorcall+0x534) [0x55f1da21bb64]
python(+0x166bf8) [0x55f1da1b4bf8]
python(PyObject_Call+0x7d) [0x55f1da18520d]
python(_PyEval_EvalFrameDefault+0x1f07) [0x55f1da2268a7]
python(_PyEval_EvalCodeWithName+0x260) [0x55f1da21a600]
python(_PyFunction_Vectorcall+0x594) [0x55f1da21bbc4]
python(_PyObject_FastCallDict+0x5f) [0x55f1da1ac62f]
python(+0x194d2b) [0x55f1da1e2d2b]
python(_PyObject_MakeTpCall+0x3bf) [0x55f1da17f13f]
python(_PyEval_EvalFrameDefault+0x4eff) [0x55f1da22989f]
python(_PyEval_EvalCodeWithName+0x260) [0x55f1da21a600]
python(_PyFunction_Vectorcall+0x534) [0x55f1da21bb64]
python(+0x166bf8) [0x55f1da1b4bf8]
python(PyObject_Call+0x7d) [0x55f1da18520d]
python(_PyEval_EvalFrameDefault+0x1f07) [0x55f1da2268a7]
python(_PyEval_EvalCodeWithName+0x260) [0x55f1da21a600]
python(_PyFunction_Vectorcall+0x594) [0x55f1da21bbc4]
python(_PyObject_FastCallDict+0x5f) [0x55f1da1ac62f]
python(+0x194d2b) [0x55f1da1e2d2b]
python(_PyObject_MakeTpCall+0x3bf) [0x55f1da17f13f]
python(_PyEval_EvalFrameDefault+0x4eff) [0x55f1da22989f]
python(_PyEval_EvalCodeWithName+0x260) [0x55f1da21a600]
python(_PyFunction_Vectorcall+0x534) [0x55f1da21bb64]
python(+0x166bf8) [0x55f1da1b4bf8]
python(PyObject_Call+0x7d) [0x55f1da18520d]
python(_PyEval_EvalFrameDefault+0x1f07) [0x55f1da2268a7]
python(_PyEval_EvalCodeWithName+0x260) [0x55f1da21a600]
python(_PyFunction_Vectorcall+0x594) [0x55f1da21bbc4]
python(_PyObject_FastCallDict+0x5f) [0x55f1da1ac62f]
python(+0x194d2b) [0x55f1da1e2d2b]
python(_PyObject_MakeTpCall+0x3bf) [0x55f1da17f13f]
python(_PyEval_EvalFrameDefault+0x4eff) [0x55f1da22989f]

[F] /home/ddp-aban/soft/src/k2/k2/csrc/fsa_utils.cu:95:k2::Fsa k2::K2FsaFromStream(std::istringstream&, int32_t, k2::Array2<int>*, int32_t, k2::Ragged<int>*) Invalid line:             1, final state has already been read, expected no more input.


[ Stack-Trace: ]
/home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/k2/lib64/libk2_log.so(k2::internal::GetStackTrace()+0x34) [0x7f71e39c4174]
/home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/k2/lib64/libk2context.so(k2::internal::Logger::~Logger()+0x2a) [0x7f71e859a35a]
/home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/k2/lib64/libk2context.so(k2::FsaFromString(std::string const&, bool, int, k2::Array2<int>*, int, k2::Ragged<int>*)+0xad2) [0x7f71e8648b52]
/home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/_k2.cpython-38-x86_64-linux-gnu.so(+0x60ae1) [0x7f71e97d2ae1]
/home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/_k2.cpython-38-x86_64-linux-gnu.so(+0x30d54) [0x7f71e97a2d54]
python(+0x13c00e) [0x55f1da18a00e]
python(_PyObject_MakeTpCall+0x3bf) [0x55f1da17f13f]
python(_PyEval_EvalFrameDefault+0x546a) [0x55f1da229e0a]
python(_PyEval_EvalCodeWithName+0x260) [0x55f1da21a600]
python(_PyFunction_Vectorcall+0x534) [0x55f1da21bb64]
python(+0x166b2e) [0x55f1da1b4b2e]
python(_PyEval_EvalFrameDefault+0x4f83) [0x55f1da229923]
python(_PyFunction_Vectorcall+0x1b7) [0x55f1da21b7e7]
python(+0x166b2e) [0x55f1da1b4b2e]
python(_PyEval_EvalFrameDefault+0x71b) [0x55f1da2250bb]
python(_PyFunction_Vectorcall+0x1b7) [0x55f1da21b7e7]
python(_PyEval_EvalFrameDefault+0x4c0) [0x55f1da224e60]
python(_PyEval_EvalCodeWithName+0x260) [0x55f1da21a600]
python(_PyFunction_Vectorcall+0x534) [0x55f1da21bb64]
python(+0x166bf8) [0x55f1da1b4bf8]
python(PyObject_Call+0x7d) [0x55f1da18520d]
python(_PyEval_EvalFrameDefault+0x1f07) [0x55f1da2268a7]
python(_PyEval_EvalCodeWithName+0x260) [0x55f1da21a600]
python(_PyFunction_Vectorcall+0x594) [0x55f1da21bbc4]
python(_PyObject_FastCallDict+0x5f) [0x55f1da1ac62f]
python(+0x194d2b) [0x55f1da1e2d2b]
python(_PyObject_MakeTpCall+0x3bf) [0x55f1da17f13f]
python(_PyEval_EvalFrameDefault+0x4eff) [0x55f1da22989f]
python(_PyEval_EvalCodeWithName+0x260) [0x55f1da21a600]
python(_PyFunction_Vectorcall+0x534) [0x55f1da21bb64]
python(+0x166bf8) [0x55f1da1b4bf8]
python(PyObject_Call+0x7d) [0x55f1da18520d]
python(_PyEval_EvalFrameDefault+0x1f07) [0x55f1da2268a7]
python(_PyEval_EvalCodeWithName+0x260) [0x55f1da21a600]
python(_PyFunction_Vectorcall+0x594) [0x55f1da21bbc4]
python(_PyObject_FastCallDict+0x5f) [0x55f1da1ac62f]
python(+0x194d2b) [0x55f1da1e2d2b]
python(_PyObject_MakeTpCall+0x3bf) [0x55f1da17f13f]
python(_PyEval_EvalFrameDefault+0x4eff) [0x55f1da22989f]
python(_PyEval_EvalCodeWithName+0x260) [0x55f1da21a600]
python(_PyFunction_Vectorcall+0x534) [0x55f1da21bb64]
python(+0x166bf8) [0x55f1da1b4bf8]
python(PyObject_Call+0x7d) [0x55f1da18520d]
python(_PyEval_EvalFrameDefault+0x1f07) [0x55f1da2268a7]
python(_PyEval_EvalCodeWithName+0x260) [0x55f1da21a600]
python(_PyFunction_Vectorcall+0x594) [0x55f1da21bbc4]
python(_PyObject_FastCallDict+0x5f) [0x55f1da1ac62f]
python(+0x194d2b) [0x55f1da1e2d2b]
python(_PyObject_MakeTpCall+0x3bf) [0x55f1da17f13f]
python(_PyEval_EvalFrameDefault+0x4eff) [0x55f1da22989f]

[F] /home/ddp-aban/soft/src/k2/k2/csrc/fsa_utils.cu:95:k2::Fsa k2::K2FsaFromStream(std::istringstream&, int32_t, k2::Array2<int>*, int32_t, k2::Ragged<int>*) Invalid line:             1, final state has already been read, expected no more input.


[ Stack-Trace: ]
/home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/k2/lib64/libk2_log.so(k2::internal::GetStackTrace()+0x34) [0x7f71e39c4174]
/home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/k2/lib64/libk2context.so(k2::internal::Logger::~Logger()+0x2a) [0x7f71e859a35a]
/home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/k2/lib64/libk2context.so(k2::FsaFromString(std::string const&, bool, int, k2::Array2<int>*, int, k2::Ragged<int>*)+0xad2) [0x7f71e8648b52]
/home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/_k2.cpython-38-x86_64-linux-gnu.so(+0x60ae1) [0x7f71e97d2ae1]
/home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/_k2.cpython-38-x86_64-linux-gnu.so(+0x30d54) [0x7f71e97a2d54]
python(+0x13c00e) [0x55f1da18a00e]
python(_PyObject_MakeTpCall+0x3bf) [0x55f1da17f13f]
python(_PyEval_EvalFrameDefault+0x546a) [0x55f1da229e0a]
python(_PyEval_EvalCodeWithName+0x260) [0x55f1da21a600]
python(_PyFunction_Vectorcall+0x534) [0x55f1da21bb64]
python(+0x166b2e) [0x55f1da1b4b2e]
python(_PyEval_EvalFrameDefault+0x4f83) [0x55f1da229923]
python(_PyFunction_Vectorcall+0x1b7) [0x55f1da21b7e7]
python(+0x166b2e) [0x55f1da1b4b2e]
python(_PyEval_EvalFrameDefault+0x71b) [0x55f1da2250bb]
python(_PyFunction_Vectorcall+0x1b7) [0x55f1da21b7e7]
python(_PyEval_EvalFrameDefault+0x4c0) [0x55f1da224e60]
python(_PyEval_EvalCodeWithName+0x260) [0x55f1da21a600]
python(_PyFunction_Vectorcall+0x534) [0x55f1da21bb64]
python(+0x166bf8) [0x55f1da1b4bf8]
python(PyObject_Call+0x7d) [0x55f1da18520d]
python(_PyEval_EvalFrameDefault+0x1f07) [0x55f1da2268a7]
python(_PyEval_EvalCodeWithName+0x260) [0x55f1da21a600]
python(_PyFunction_Vectorcall+0x594) [0x55f1da21bbc4]
python(_PyObject_FastCallDict+0x5f) [0x55f1da1ac62f]
python(+0x194d2b) [0x55f1da1e2d2b]
python(_PyObject_MakeTpCall+0x3bf) [0x55f1da17f13f]
python(_PyEval_EvalFrameDefault+0x4eff) [0x55f1da22989f]
python(_PyEval_EvalCodeWithName+0x260) [0x55f1da21a600]
python(_PyFunction_Vectorcall+0x534) [0x55f1da21bb64]
python(+0x166bf8) [0x55f1da1b4bf8]
python(PyObject_Call+0x7d) [0x55f1da18520d]
python(_PyEval_EvalFrameDefault+0x1f07) [0x55f1da2268a7]
python(_PyEval_EvalCodeWithName+0x260) [0x55f1da21a600]
python(_PyFunction_Vectorcall+0x594) [0x55f1da21bbc4]
python(_PyObject_FastCallDict+0x5f) [0x55f1da1ac62f]
python(+0x194d2b) [0x55f1da1e2d2b]
python(_PyObject_MakeTpCall+0x3bf) [0x55f1da17f13f]
python(_PyEval_EvalFrameDefault+0x4eff) [0x55f1da22989f]
python(_PyEval_EvalCodeWithName+0x260) [0x55f1da21a600]
python(_PyFunction_Vectorcall+0x534) [0x55f1da21bb64]
python(+0x166bf8) [0x55f1da1b4bf8]
python(PyObject_Call+0x7d) [0x55f1da18520d]
python(_PyEval_EvalFrameDefault+0x1f07) [0x55f1da2268a7]
python(_PyEval_EvalCodeWithName+0x260) [0x55f1da21a600]
python(_PyFunction_Vectorcall+0x594) [0x55f1da21bbc4]
python(_PyObject_FastCallDict+0x5f) [0x55f1da1ac62f]
python(+0x194d2b) [0x55f1da1e2d2b]
python(_PyObject_MakeTpCall+0x3bf) [0x55f1da17f13f]
python(_PyEval_EvalFrameDefault+0x4eff) [0x55f1da22989f]

............str(fsa0) ==  k2.Fsa: 0 1 4 1 0.1
1 2 5 2 0.2
2 3 -1 -1 0.3
3
properties_str = "Valid|Nonempty|TopSorted|TopSortedAndAcyclic|ArcSorted|ArcSortedAndDeterministic|EpsilonFree|MaybeAccessible|MaybeCoaccessible".
aux_labels: tensor([ 1,  2, -1], dtype=torch.int32)
str(fsa1) ==  k2.Fsa: 0 1 4 1 0.1
1 2 5 2 0.2
2 3 -1 -1 0.3
3
properties_str = "Valid|Nonempty|TopSorted|TopSortedAndAcyclic|ArcSorted|ArcSortedAndDeterministic|EpsilonFree|MaybeAccessible|MaybeCoaccessible".
aux_labels: tensor([ 1,  2, -1], dtype=torch.int32)
.[ [ 0 1 1 0.1 0 2 2 0.2 ] [ 1 2 3 0.3 ] [ 2 3 -1 0.4 ] [ ] ]
........fsa.ragged1 =  RaggedTensor([[],
              [],
              [20, 30],
              [],
              [],
              [],
              [],
              []], dtype=torch.int32)
fsa.ragged2 =  RaggedTensor([[],
              [],
              [40],
              [],
              [],
              [],
              [],
              []], dtype=torch.int32)
fsa =  0 1 2 22 101 [ ] [ ] -1.2
0 2 10 100 102 [ ] [ ] -2.2
1 6 -1 16 103 [ 20 30 ] [ 40 ] -4.2
1 3 3 33 104 [ ] [ ] -3.2
2 6 -1 26 105 [ ] [ ] -5.2
2 4 2 22 106 [ ] [ ] -6.2
3 6 -1 36 107 [ ] [ ] -7.2
5 0 1 50 108 [ ] [ ] -8.2
6
.....
----------------------------------------------------------------------
Ran 31 tests in 2.278s

OK
```

bellow env

```
$ python -m k2.version 
Collecting environment information...

k2 version: 1.17
Build type: Release
Git SHA1: 9e88318adfd7c80290a96f8a888d279d45dc1564
Git date: Mon Jul 18 16:26:06 2022
Cuda used to build k2: 11.3
cuDNN used to build k2: 8.3.2
Python version used to build k2: 3.8
OS used to build k2: 
CMake version: 3.23.2
GCC version: 8.3.1
CMAKE_CUDA_FLAGS:  -Wno-deprecated-gpu-targets   -lineinfo --expt-extended-lambda -use_fast_math -Xptxas=-w  --expt-extended-lambda -gencode arch=compute_86,code=sm_86 -DONNX_NAMESPACE=onnx_c2 -gencode arch=compute_86,code=sm_86 -Xcudafe --diag_suppress=cc_clobber_ignored,--diag_suppress=integer_sign_change,--diag_suppress=useless_using_declaration,--diag_suppress=set_but_not_used,--diag_suppress=field_without_dll_interface,--diag_suppress=base_class_has_different_dll_interface,--diag_suppress=dll_interface_conflict_none_assumed,--diag_suppress=dll_interface_conflict_dllexport_assumed,--diag_suppress=implicit_return_from_non_void_function,--diag_suppress=unsigned_compare_with_zero,--diag_suppress=declared_but_not_referenced,--diag_suppress=bad_friend_decl --expt-relaxed-constexpr --expt-extended-lambda -D_GLIBCXX_USE_CXX11_ABI=0 --compiler-options -Wall  --compiler-options -Wno-strict-overflow  --compiler-options -Wno-unknown-pragmas 
CMAKE_CXX_FLAGS:  -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-unused-variable  -Wno-strict-overflow 
PyTorch version used to build k2: 1.12.0
PyTorch is using Cuda: 11.3
NVTX enabled: True
With CUDA: True
Disable debug: True
Sync kernels : False
Disable checks: False
Max cpu memory allocate: 214748364800 bytes (or 200.0 GB)
k2 abort: False
__file__: /home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/k2/version/version.py
_k2.__file__: /home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/_k2.cpython-38-x86_64-linux-gnu.so

```

```
$ python3 -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 1.12.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
Clang version: Could not collect
CMake version: version 3.23.2
Libc version: glibc-2.17

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.18.9-1.el7.elrepo.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.3.58
GPU models and configuration: 
GPU 0: NVIDIA A10
GPU 1: NVIDIA A10
GPU 2: NVIDIA A10
GPU 3: NVIDIA A10
GPU 4: NVIDIA A10
GPU 5: NVIDIA A10
GPU 6: NVIDIA A10
GPU 7: NVIDIA A10
GPU 8: NVIDIA A10
GPU 9: NVIDIA A10

Nvidia driver version: 515.48.07
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] k2==1.17.dev20220721+cuda11.3.torch1.12.0
[pip3] numpy==1.22.3
[pip3] torch==1.12.0
[pip3] torch-tb-profiler==0.4.0
[pip3] torchaudio==0.12.0
[pip3] torchvision==0.13.0
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               11.3.1               h2bc3f7f_2    defaults
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] k2                        1.17.dev20220721+cuda11.3.torch1.12.0          pypi_0    pypi
[conda] mkl                       2021.4.0           h06a4308_640    defaults
[conda] mkl-service               2.4.0            py38h7f8727e_0    defaults
[conda] mkl_fft                   1.3.1            py38hd3c417c_0    defaults
[conda] mkl_random                1.2.2            py38h51133e4_0    defaults
[conda] numpy                     1.22.3           py38he7a7128_0    defaults
[conda] numpy-base                1.22.3           py38hf524024_0    defaults
[conda] pytorch                   1.12.0          py3.8_cuda11.3_cudnn8.3.2_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch-tb-profiler         0.4.0                    pypi_0    pypi
[conda] torchaudio                0.12.0               py38_cu113    pytorch
[conda] torchvision               0.13.0               py38_cu113    pytorch
```

**Comment by csukuangfj** [comment]
At the end of the test, it says OK.

**Comment by ahban** [comment]
When I test k2 using the aishell eg in the icefall, I failed to compile HLG.fst. a similar exception is below. 
```
$ ./prepare.sh --stage 7 2>&1 | head -n 100
2022-07-26 10:03:47 (prepare.sh:45:main) dl_dir: /home/ddp-aban/devel/icefall/egs/aishell/ASR/download
2022-07-26 10:03:47 (prepare.sh:194:main) Stage 7: Prepare G
2022-07-26 10:03:47 (prepare.sh:210:main) Stage 8: Compile HLG
2022-07-26 10:03:48,647 INFO [compile_hlg.py:145] Processing data/lang_phone
2022-07-26 10:03:48,827 INFO [lexicon.py:176] Loading pre-compiled data/lang_phone/Linv.pt
2022-07-26 10:03:48,869 INFO [compile_hlg.py:64] Building ctc_topo. max_token_id: 219
2022-07-26 10:03:48,912 INFO [compile_hlg.py:73] Loading G_3_gram.fst.txt
[F] /home/ddp-aban/soft/src/k2/k2/csrc/fsa_utils.cu:295:void k2::OpenFstStreamReader::ProcessLine(std::string&) Invalid line: 3 0       137054  0, eof=true, fail=true, src_state=3, dest_state=0


[ Stack-Trace: ]
/home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/k2/lib64/libk2_log.so(k2::internal::GetStackTrace()+0x34) [0x7f01207ff174]
/home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/k2/lib64/libk2context.so(k2::internal::Logger::~Logger()+0x2a) [0x7f012116b35a]
/home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/k2/lib64/libk2context.so(k2::OpenFstStreamReader::ProcessLine(std::string&)+0x82a) [0x7f0121271baa]
/home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/k2/lib64/libk2context.so(k2::FsaFromString(std::string const&, bool, int, k2::Array2<int>*, int, k2::Ragged<int>*)+0x96e) [0x7f01212199ee]
/home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/_k2.cpython-38-x86_64-linux-gnu.so(+0x60ae1) [0x7f01223a3ae1]
/home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/_k2.cpython-38-x86_64-linux-gnu.so(+0x30d54) [0x7f0122373d54]
python3(+0x13c00e) [0x5598cf5bc00e]
python3(_PyObject_MakeTpCall+0x3bf) [0x5598cf5b113f]
python3(_PyEval_EvalFrameDefault+0x546a) [0x5598cf65be0a]
python3(_PyEval_EvalCodeWithName+0x260) [0x5598cf64c600]
python3(_PyFunction_Vectorcall+0x594) [0x5598cf64dbc4]
python3(+0x166b2e) [0x5598cf5e6b2e]
python3(_PyEval_EvalFrameDefault+0x1510) [0x5598cf657eb0]
python3(_PyEval_EvalCodeWithName+0x260) [0x5598cf64c600]
python3(_PyFunction_Vectorcall+0x594) [0x5598cf64dbc4]
python3(+0x166b2e) [0x5598cf5e6b2e]
python3(_PyEval_EvalFrameDefault+0x1510) [0x5598cf657eb0]
python3(_PyFunction_Vectorcall+0x1b7) [0x5598cf64d7e7]
python3(_PyEval_EvalFrameDefault+0x71b) [0x5598cf6570bb]
python3(_PyFunction_Vectorcall+0x1b7) [0x5598cf64d7e7]
python3(_PyEval_EvalFrameDefault+0x71b) [0x5598cf6570bb]
python3(_PyEval_EvalCodeWithName+0x260) [0x5598cf64c600]
python3(PyEval_EvalCode+0x23) [0x5598cf64deb3]
python3(+0x242622) [0x5598cf6c2622]
python3(+0x2531d2) [0x5598cf6d31d2]
python3(+0x25636b) [0x5598cf6d636b]
python3(PyRun_SimpleFileExFlags+0x1bf) [0x5598cf6d654f]
python3(Py_RunMain+0x3a9) [0x5598cf6d6a29]
python3(Py_BytesMain+0x39) [0x5598cf6d6c29]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x7f01b7f99555]
python3(+0x1f9ad7) [0x5598cf679ad7]

Traceback (most recent call last):
  File "/home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/k2/fsa.py", line 1280, in from_str
    ragged_labels) = _k2.fsa_from_str(s, num_aux_labels,
RuntimeError: 
    Some bad things happened. Please read the above error messages and stack
    trace. If you are using Python, the following command may be helpful:

      gdb --args python /path/to/your/code.py

    (You can use `gdb` to debug the code. Please consider compiling
    a debug version of k2.).

    If you are unable to fix it, please open an issue at:

      https://github.com/k2-fsa/k2/issues/new
    

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./local/compile_hlg.py", line 160, in <module>
    main()
  File "./local/compile_hlg.py", line 148, in main
    HLG = compile_HLG(lang_dir)
  File "./local/compile_hlg.py", line 75, in compile_HLG
    G = k2.Fsa.from_openfst(f.read(), acceptor=False)
  File "/home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/k2/fsa.py", line 1352, in from_openfst
    return Fsa.from_str(s, acceptor, num_aux_labels,
  File "/home/ddp-aban/soft/anaconda3/envs/k2-1.12/lib/python3.8/site-packages/k2-1.17.dev20220721+cuda11.3.torch1.12.0-py3.8-linux-x86_64.egg/k2/fsa.py", line 1293, in from_str
    raise ValueError(f'The following is not a valid Fsa {o}(with '
ValueError: The following is not a valid Fsa in the OpenFst format (with num_aux_labels=1): 
1       138369  148     148     4.71846
1       139099  150     150     9.38227
1       145617  151     151     11.5317
1       142247  157     157     12.2264
1       137780  160     160     13.1849
1       147494  161     161     13.1046
1       138161  169     169     9.4811
1       140181  172     172     11.735
1       137779  174     174     13.1849
1       141808  196     196     12.1455
1       141321  216     216     10.7594
1       141061  220     220     9.20475
1       137778  234     234     13.1849
1       146730  235     235     13.1046
1       147493  236     236     13.1046
1       146122  237     237     12.9346
1       146121  239     239     11.5515
1       147492  241     241     13.1046
1       144446  245     245     11.4923
1       143679  246     246     11.4642
1       143880  248     248     10.8871
1       143473  249     249     10.8842
1       143879  252     252     11.4352
1       144137  253     253     11.4856
1       144445  254     254     11.5261
1       145616  255     255     10.9302
```

**Comment by csukuangfj** [comment]
> When I test k2 using the aishell eg in the icefall, I failed to compile HLG.fst. a similar exception is below.


Could you try https://github.com/k2-fsa/k2/pull/1002 ?

You can use
```
# Assume you have cloned k2 to /path/to/k2
cd /path/to/k2
git remote add fj https://github.com/csukuangfj/k2
git fetch fj
git checkout fj/fix-parsing-fsa
python3 setup.py install
```

and retry again?

**Comment by ahban** [comment]
after reinstall, it works for aishell/asr now. Thanks~

**Comment by csukuangfj** [comment]
@ahban 

Could you help us debug this problem with gdb?
The following are the commands that you need:

```bash
cd /path/to/k2
git checkout master # switch to the master branch
export K2_CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Debug"
export K2_MAKE_ARGS="=-j10"

rm -rf build
python3 setup.py install
```

After installing k2, you can use the following command to run icefall:
```
cd /path/to/icefall/egs/aishell/ASR
gdb --args python3 ./local/compile_hlg.py --lang-dir data/lang_phone

# Then it will enter gdb
(gdb) catch throw
(gdb) run
# And when it throws
# do
(gdb) bt

```

**Comment by wangtiance** [comment]
I did try the above and got the following result. Not sure if it helps. 
The only problematic version is the conda version. If I built it from the source then it won't happen
k2                        1.17.dev20220704 cuda11.3_py3.9_torch1.12.0    https://conda.anaconda.org/k2-fsa
[gdb.txt](https://github.com/k2-fsa/k2/files/9305805/gdb.txt)

**Comment by wangtiance** [comment]
The content of scratch.py is
`import k2
import torch

with open("data/lm/test.txt") as f:
    G = k2.Fsa.from_openfst(f.read(), acceptor=False)
    torch.save(G.as_dict(), "data/lm/test.pt")`
