### ISSUE TITLE
importError:version `GLIBCXX_3.4.30' not found

### ISSUE THREAD

**Issue by shanguanma** [k2-fsa/k2#1045]
I install k2 in new server cluster environment, it's os is Rocky Linux release 8.6 (Green Obsidian)
I using the below command to install k2
```
conda create -n k2-fsa1 python=3.8 -y
conda activate k2-fsa1
conda install -c conda-forge cudnn==8.2.1
conda install pytorch==1.12.0 cudatoolkit=11.3 -c pytorch
conda install -c k2-fsa -c pytorch -c conda-forge k2 python=3.8 cudatoolkit=11.3 pytorch=1.12.0
```

But it occurs error when I import k2, the error log is as follows:
```
>>> import k2
Traceback (most recent call last):
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/k2-fsa1/lib/python3.8/site-packages/k2/__init__.py", line 24, in <module>
    from _k2 import DeterminizeWeightPushingType
ImportError: /mntnfs/lee_data1/maduo/anaconda3/envs/k2-fsa1/lib/python3.8/site-packages/torch/lib/../../../../libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /mntnfs/lee_data1/maduo/anaconda3/envs/k2-fsa1/lib/python3.8/site-packages/k2/lib/libk2context.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mntnfs/lee_data1/maduo/anaconda3/envs/k2-fsa1/lib/python3.8/site-packages/k2/__init__.py", line 30, in <module>
    raise ImportError(
ImportError: /mntnfs/lee_data1/maduo/anaconda3/envs/k2-fsa1/lib/python3.8/site-packages/torch/lib/../../../../libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /mntnfs/lee_data1/maduo/anaconda3/envs/k2-fsa1/lib/python3.8/site-packages/k2/lib/libk2context.so)
Note: If you're using anaconda and importing k2 on MacOS,
      you can probably fix this by setting the environment variable:
  export DYLD_LIBRARY_PATH=$CONDA_PREFIX/lib/python3.8/site-packages:$DYLD_LIBRARY_PATH
```

**Comment by csukuangfj** [comment]
What is the output of?

```bash
strings /mntnfs/lee_data1/maduo/anaconda3/envs/k2-fsa1/lib | grep GLIBCXX
```

I guess the reason is that your system is too new. Install k2 from source will fix the issue.
The conda package is built using ubuntu 18.04.

**Comment by shanguanma** [comment]
@csukuangfj ，thanks for your reply, 
```
strings /mntnfs/lee_data1/maduo/anaconda3/envs/k2-fsa1/lib/python3.8/site-packages/torch/lib/../../../../libstdc++.so.6  | grep GLIBC
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_3.4.29
GLIBC_2.2.5
GLIBC_2.3
GLIBC_2.14
GLIBC_2.6
GLIBC_2.4
GLIBC_2.16
GLIBC_2.17
GLIBC_2.3.2
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

however , I have use the below command to solve it.

```
conda install -c conda-forge gcc=12.1.0
```

After, it's output is as follows:
````
strings /mntnfs/lee_data1/maduo/anaconda3/envs/k2-fsa1/lib/python3.8/site-packages/torch/lib/../../../../libstdc++.so.6  | grep GLIBC
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_3.4.29
GLIBCXX_3.4.30
GLIBC_2.2.5
GLIBC_2.3
GLIBC_2.6
GLIBC_2.4
GLIBC_2.3.2
GLIBCXX_DEBUG_MESSAGE_LENGTH
````

**Comment by shanguanma** [comment]
Solve it , colse it.

**Comment by csukuangfj** [comment]
> however , I have use the below command to solve it.

Thanks for the solution and glad to see that you fix it by yourself.
