### ISSUE TITLE
Issue with importing k2 compiled from source

### ISSUE THREAD

**Issue by pzelasko** [k2-fsa/k2#1053]
### Description

I compiled the latest k2 master (`125d34703f898b5ca54f6f4a925f2bc2d7a5ba98`) with CUDA support, PyTorch 1.12.1, and Python 3.8. I'm trying to import it and then it crashes after trying to find some symbol. 

Not sure what went wrong. LMK if I can provide more info that is helpful.

### Output

```
$ python -c 'import k2'
Traceback (most recent call last):
  File "/fsx/home/pzelasko/meaning/env10/lib/python3.8/site-packages/k2/__init__.py", line 24, in <module>
    from _k2 import DeterminizeWeightPushingType
ImportError: /fsx/home/pzelasko/meaning/env10/lib/python3.8/site-packages/_k2.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/fsx/home/pzelasko/meaning/env10/lib/python3.8/site-packages/k2/__init__.py", line 30, in <module>
    raise ImportError(
ImportError: /fsx/home/pzelasko/meaning/env10/lib/python3.8/site-packages/_k2.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE
Note: If you're using anaconda and importing k2 on MacOS,
      you can probably fix this by setting the environment variable:
  export DYLD_LIBRARY_PATH=$CONDA_PREFIX/lib/python3.8/site-packages:$DYLD_LIBRARY_PATH
```

### Versions

```
$ python collect_env.py
Collecting environment information...
PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.31

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.11.0-1020-aws-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: 11.4.48
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] k2==1.19.dev20220908+cuda11.3.torch1.12.1
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.3
[pip3] torch==1.12.1
[pip3] torch-ort==1.12.0
[pip3] torch-ort-infer==1.12.0
[pip3] torchaudio==0.12.1
[pip3] torchmetrics==0.7.2
[pip3] torchvision==0.13.1
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h2bc3f7f_2
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] k2                        1.19.dev20220908+cuda11.3.torch1.12.1          pypi_0    pypi
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py38h7f8727e_0
[conda] mkl_fft                   1.3.1            py38hd3c417c_0
[conda] mkl_random                1.2.2            py38h51133e4_0
[conda] numpy                     1.22.3           py38he7a7128_0
[conda] numpy-base                1.22.3           py38hf524024_0
[conda] pytorch                   1.12.1          py3.8_cuda11.3_cudnn8.3.2_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch-ort                 1.12.0                   pypi_0    pypi
[conda] torch-ort-infer           1.12.0                   pypi_0    pypi
[conda] torchaudio                0.12.1               py38_cu113    pytorch
[conda] torchmetrics              0.7.2                    pypi_0    pypi
[conda] torchvision               0.13.1               py38_cu113    pytorch
```

**Comment by csukuangfj** [comment]
Can you check that you have unis talled your previous versions of k2? That is, there is no
_k2.xxxx.so left.

**Comment by csukuangfj** [comment]
The import error is very likely caused by your previous installed k2, which was compiled using a different version of PyTorch.

**Comment by csukuangfj** [comment]
You may find

https://github.com/k2-fsa/sherpa/issues/53

helpful.

**Comment by pzelasko** [comment]
Thanks, this helped. It actually turned out to be a "dirty" k2 directory that had some object files compiled against an older torch version, and some against the newer one. I cleaned it up, recompiled, and now it works.
