### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by danpovey** [k2-fsa/k2#402]
```
de-74279-k2-dev-0929153814-7686b86bc5-qbfjq:build:   /usr/bin/python3.8 "/ceph-dan/k2/k2/python/tests/ragged_shape_test.py"
EE
======================================================================
ERROR: test_ragged_shape (__main__.TestRaggedShape)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ceph-dan/k2/k2/python/tests/ragged_shape_test.py", line 33, in test_ragged_shape
    shape = k2.RaggedShape(src)
AttributeError: module 'k2' has no attribute 'RaggedShape'

```

```
   /usr/bin/python3.8 "/ceph-dan/k2/k2/python/tests/remove_epsilon_test.py"
E
======================================================================
ERROR: test1 (__main__.TestRemoveEpsilon)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ceph-dan/k2/k2/python/tests/remove_epsilon_test.py", line 40, in test1
    dest = k2.remove_epsilon(fsa)
  File "/ceph-dan/k2/build/lib/k2/fsa_algo.py", line 282, in remove_epsilon
    out_fsa = Fsa(ragged_arc)
  File "/ceph-dan/k2/build/lib/k2/fsa.py", line 186, in __init__
    self._tensor_attr['scores'] = _as_float(self.arcs.values()[:, -1])
AttributeError: 'tuple' object has no attribute 'values'

----------------------------------------------------------------------
Ran 1 test in 0.001s

```

**Comment by danpovey** [comment]
Seems to have been a local path issue.

**Comment by csukuangfj** [comment]
I guess you have a directory `build/lib/k2` which is different from `k2/k2/python/k2` or is different from the one you installed locally.
