### ISSUE TITLE
k2.linear_fsa doesn't work with torch.device

### ISSUE THREAD

**Issue by GNroy** [k2-fsa/k2#835]
With k2 v1.8, `k2.linear_fsa` drops `TypeError` when used with `torch.device`:
```
>>> import k2                                                                                                                                        
>>> import torch
>>> device = torch.device("cuda:0")
>>> a = [[1,2,4,2], [3,1,1]]
>>> # doesn't work
>>> b = k2.linear_fsa(a, device)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/k2-1.8.dev20210927+cuda11.2.torch1.9.0a0-py3.8-linux-x86_64.egg/k2/fsa_algo.py", line 66, in linear_fsa
    ragged_arc = _k2.linear_fsa(labels, device)
TypeError: linear_fsa(): incompatible function arguments. The following argument types are supported:
    1. (labels: k2::RaggedAny, device: Optional[c10::Device] = None) -> k2::Ragged<k2::Arc>
    2. (labels: List[int], device: Optional[c10::Device] = None) -> k2::Ragged<k2::Arc>
    3. (labels: List[int], device: Optional[str] = None) -> k2::Ragged<k2::Arc>
    4. (labels: List[List[int]], device: Optional[c10::Device] = None) -> k2::Ragged<k2::Arc>
    5. (labels: List[List[int]], device: Optional[str] = None) -> k2::Ragged<k2::Arc>

Invoked with: [[1, 2, 4, 2], [3, 1, 1]], device(type='cuda', index=0)
>>> # works
>>> b = k2.linear_fsa(a).to(device)
>>> b
<k2.fsa.Fsa object at 0x7f6213113310>
```

**Comment by GNroy** [comment]
@csukuangfj thanks!
I confirm, everything works fine in a clear environment (as in https://github.com/k2-fsa/k2/issues/834#issuecomment-929128559).

**Comment by csukuangfj** [comment]
> @csukuangfj thanks! I confirm, everything works fine in a clear environment (as in [#834 (comment)](https://github.com/k2-fsa/k2/issues/834#issuecomment-929128559)).

Thanks for the feedback.
