### ISSUE TITLE
Prebuilt packages compatible with older OS

### ISSUE THREAD

**Issue by pzelasko** [k2-fsa/k2#888]
We’re facing some issues with pip and conda installed k2 packages on the CLSP grid since the GitHub actions CI upgraded Ubuntu to 18.04. The issue is that our Debian 4.9 system has glibc version older than 2.27. Could you prebuild and upload the packages for older systems like this? I can provide more info if needed.

**Comment by csukuangfj** [comment]
`GitHub actions` does not support Ubuntu 16.04 anymore.

I have tried to use a docker image with Ubuntu 16.04 to build k2 with GitHub actions but it is failed with the following error message and I have no idea how to fix it.
```
Copying /__w/k2/k2 to /__w/k2/k2/3/envs/k3/conda-bld/k2_1636875528120/work/
Traceback (most recent call last):
  File "/__w/k2/k2/3/envs/k3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/__w/k2/k2/3/envs/k3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 481, in main
    execute(sys.argv[1:])
  File "/__w/k2/k2/3/envs/k3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 472, in execute
    verify=args.verify, variants=args.variants, cache_dir=args.cache_dir)
  File "/__w/k2/k2/3/envs/k3/lib/python3.6/site-packages/conda_build/api.py", line 195, in build
    variants=variants
  File "/__w/k2/k2/3/envs/k3/lib/python3.6/site-packages/conda_build/build.py", line 3090, in build_tree
    notest=notest,
  File "/__w/k2/k2/3/envs/k3/lib/python3.6/site-packages/conda_build/build.py", line 2135, in build
    try_download(m, no_download_source=False, raise_error=True)
  File "/__w/k2/k2/3/envs/k3/lib/python3.6/site-packages/conda_build/render.py", line 650, in try_download
    source.provide(metadata)
  File "/__w/k2/k2/3/envs/k3/lib/python3.6/site-packages/conda_build/source.py", line 903, in provide
    locking=metadata.config.locking, clobber=True)
  File "/__w/k2/k2/3/envs/k3/lib/python3.6/site-packages/conda_build/utils.py", line 571, in copy_into
    merge_tree(src, dst, symlinks, timeout=timeout, lock=lock, locking=locking, clobber=clobber)
  File "/__w/k2/k2/3/envs/k3/lib/python3.6/site-packages/conda_build/utils.py", line 674, in merge_tree
    "  dst: {1}".format(src, dst))
AssertionError: Can't merge/copy source into subdirectory of itself.  Please create separate spaces for these things.
  src: /__w/k2/k2
  dst: /__w/k2/k2/3/envs/k3/conda-bld/k2_1636875528120/work
Error: Process completed with exit code 1.
```

The error log can be found by visiting https://github.com/csukuangfj/k2/actions/workflows/build_conda_cpu_ubuntu.yml

**Comment by pzelasko** [comment]
That is weird, it looks like you’re trying to copy a directory into a sub-directory within that directory. Maybe there are some env vars or docker args related to workdir path that could be changed to amend this. But I never built any anaconda package so I wouldn’t know what they are..

**Comment by csukuangfj** [comment]
I will try to fix it.

**Comment by pzelasko** [comment]
Thanks!
