### ISSUE TITLE
K2 compilation from source throws compiler internal error (maybe source can be modified to fix the issue)

### ISSUE THREAD

**Issue by ngoel17** [k2-fsa/k2#903]
Scanning dependencies of target k2_log
[  4%] Building CUDA object k2/csrc/CMakeFiles/k2_log.dir/log.cu.o
/usr/include/c++/10/chrono: In substitution of ‘template<class _Rep, class _Period> template<class _Period2> using __is_harmonic = std::__bool_constant<(std::ratio<((_Period2::num / std::chrono::duration<_Rep, _Period>::_S_gcd(_Period2::num, _Period::num)) * (_Period::den / std::chrono::duration<_Rep, _Period>::_S_gcd(_Period2::den, _Period::den))), ((_Period2::den / std::chrono::duration<_Rep, _Period>::_S_gcd(_Period2::den, _Period::den)) * (_Period::num / std::chrono::duration<_Rep, _Period>::_S_gcd(_Period2::num, _Period::num)))>::den == 1)> [with _Period2 = _Period2; _Rep = _Rep; _Period = _Period]’:
/usr/include/c++/10/chrono:473:154:   required from here
/usr/include/c++/10/chrono:428:27: internal compiler error: Segmentation fault
  428 |  _S_gcd(intmax_t __m, intmax_t __n) noexcept
      |                           ^~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-10/README.Bugs> for instructions.
make[3]: *** [k2/csrc/CMakeFiles/k2_log.dir/build.make:82: k2/csrc/CMakeFiles/k2_log.dir/log.cu.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:2363: k2/csrc/CMakeFiles/k2_log.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:3421: k2/python/csrc/CMakeFiles/_k2.dir/rule] Error 2
make: *** [Makefile:1399: _k2] Error 2
Traceback (most recent call last):
  File "/home/ngoel-00171/k2/setup.py", line 198, in <module>
    setuptools.setup(
  File "/home/ngoel-00171/anaconda3/envs/k2/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/ngoel-00171/anaconda3/envs/k2/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/ngoel-00171/anaconda3/envs/k2/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/ngoel-00171/anaconda3/envs/k2/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ngoel-00171/anaconda3/envs/k2/lib/python3.9/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/ngoel-00171/anaconda3/envs/k2/lib/python3.9/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/ngoel-00171/anaconda3/envs/k2/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/ngoel-00171/anaconda3/envs/k2/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ngoel-00171/anaconda3/envs/k2/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/ngoel-00171/anaconda3/envs/k2/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/ngoel-00171/anaconda3/envs/k2/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/ngoel-00171/anaconda3/envs/k2/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ngoel-00171/anaconda3/envs/k2/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/ngoel-00171/anaconda3/envs/k2/lib/python3.9/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/ngoel-00171/anaconda3/envs/k2/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/ngoel-00171/anaconda3/envs/k2/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ngoel-00171/anaconda3/envs/k2/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/ngoel-00171/anaconda3/envs/k2/lib/python3.9/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/ngoel-00171/anaconda3/envs/k2/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/ngoel-00171/anaconda3/envs/k2/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/ngoel-00171/k2/setup.py", line 146, in build_extension
    raise Exception('Failed to build k2')
Exception: Failed to build k2

k2 version: 1.11
Build type: Release
Git SHA1: 
Git date: 
Cuda used to build k2: 
cuDNN used to build k2: 
Python version used to build k2: 3.9
OS used to build k2: Ubuntu 16.04.7 LTS
CMake version: 3.18.2
GCC version: 5.4.0
CMAKE_CUDA_FLAGS: 
CMAKE_CXX_FLAGS:  -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-unused-variable -Wno-strict-overflow
PyTorch version used to build k2: 1.10.0
PyTorch is using Cuda: 
NVTX enabled: False
With CUDA: False
Disable debug: True
Sync kernels : False
Disable checks: False
    
Collecting environment information...
PyTorch version: 1.10.1
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 21.04 (x86_64)
GCC version: (Ubuntu 10.3.0-1ubuntu1) 10.3.0
Clang version: Could not collect
CMake version: version 3.18.4
Libc version: glibc-2.33

Python version: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:23:11)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.11.0-1026-gcp-x86_64-with-glibc2.33
Is CUDA available: False
CUDA runtime version: 11.3.58
GPU models and configuration: GPU 0: NVIDIA Tesla V100-SXM2-16GB
Nvidia driver version: 465.19.01
cuDNN version: Probably one of the following:
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.10.1
[pip3] torchaudio==0.10.1
[pip3] torchvision==0.11.2
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   2.0                           0    pytorch
[conda] cudatoolkit               11.3.1               ha36c431_9    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] k2                        1.11.dev20211208 cpu_py3.9_torch1.10  [cpuonly]  k2-fsa
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.21.2           py39h20f2e39_0  
[conda] numpy-base                1.21.2           py39h79a1101_0  
[conda] pytorch                   1.10.1              py3.9_cpu_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchaudio                0.10.1                 py39_cpu  [cpuonly]  pytorch
[conda] torchvision               0.11.2                 py39_cpu  [cpuonly]  pytorch

**Comment by csukuangfj** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100102
shows it is a bug only in GCC 10.3, and it works for GCC 10.2
